# Generated by Django 4.0.5 on 2022-07-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_price', models.IntegerField(default=0)),
                ('product_detail', models.TextField()),
                ('product_image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
