# Generated by Django 4.1.7 on 2023-03-27 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email_id',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone_no',
            new_name='phone',
        ),
    ]
